### ISSUE TITLE
OS: utility `npm` doesn't work

### ISSUE THREAD

**Issue by xeffyr** [xeffyr/alpine-term#8]
Node.js package manager doesn't work.

Problem is specific to Alpine Term. I can't reproduce it on *same* OS image running on PC (with and without KVM) and QEMU options equivalent to ones used in this application. However on PC QEMU version is 4.2.0 while Alpine Term uses 4.1.1.

I don't know what causing this issue. It may be specific to QEMU build or may happen due to bug in Node.js which can be triggered only in systems with very low performance (race condition???).

```
buffer.js:607
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:607:37)
    at Buffer.toString (buffer.js:804:14)
    at Object.readFileSync (fs.js:404:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:22)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_OUT_OF_RANGE'
}
```

Used Node.js version: `v12.18.0`.

**Comment by xeffyr** [comment]
Updating QEMU to v4.2.1 fixes the issue but I need to be sure that it is stable enough (i.e. not worse than v4.1.1) to be included in next Alpine Term release.
